spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfoliodb
    username: gerard
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: 
      - classpath:scripts/schema.sql  
  mvc:
    servlet:
      path: /
